# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.5"

gem "rails", "~> 6.0.1"

gem "bootsnap", require: false
gem "pg", "~> 1.2.3"
gem "puma", "~> 4.3.3"
gem "rubocop-performance", require: false
gem "rubocop-rails", require: false

gem "active_model_serializers", "~> 0.10.0"
gem "dotenv-rails", "~> 2.7.5"
gem "minitest-rails", "~> 6.0.0"
gem "oj"

gem "faraday"
gem "faraday-cookie_jar"

group :development do
  gem "awesome_print", "~> 1.8.0"
  gem "better_errors", "~> 2.8.0"
  gem "binding_of_caller", "~> 0.8.0"
  gem "bullet", "~> 6.1.0"
  gem "listen", "~> 3.2.1"
  gem "spring"
  gem "table_print", "~> 1.5.6"
  gem "web-console", "~> 4.0.1"
end

group :development, :test do
  gem "byebug", "~> 11.1.1", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
end
